services:
  haproxy:
    image: haproxy
    container_name: haproxy
    restart: always
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/vendor_data.lua:/usr/local/etc/haproxy/vendor_data.lua:ro
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
